/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapsRouteImport } from './routes/roadmaps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddSkillRouteImport } from './routes/add-skill'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesWebDevRouteImport } from './routes/templates.web-dev'
import { Route as TemplatesUiUxRouteImport } from './routes/templates.ui-ux'
import { Route as TemplatesDataScienceRouteImport } from './routes/templates.data-science'
import { Route as TemplatesCourseIdRouteImport } from './routes/templates.course.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapsRoute = RoadmapsRouteImport.update({
  id: '/roadmaps',
  path: '/roadmaps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddSkillRoute = AddSkillRouteImport.update({
  id: '/add-skill',
  path: '/add-skill',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesWebDevRoute = TemplatesWebDevRouteImport.update({
  id: '/templates/web-dev',
  path: '/templates/web-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesUiUxRoute = TemplatesUiUxRouteImport.update({
  id: '/templates/ui-ux',
  path: '/templates/ui-ux',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesDataScienceRoute = TemplatesDataScienceRouteImport.update({
  id: '/templates/data-science',
  path: '/templates/data-science',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesCourseIdRoute = TemplatesCourseIdRouteImport.update({
  id: '/templates/course/$id',
  path: '/templates/course/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-skill': typeof AddSkillRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/roadmaps': typeof RoadmapsRoute
  '/settings': typeof SettingsRoute
  '/templates/data-science': typeof TemplatesDataScienceRoute
  '/templates/ui-ux': typeof TemplatesUiUxRoute
  '/templates/web-dev': typeof TemplatesWebDevRoute
  '/templates/course/$id': typeof TemplatesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-skill': typeof AddSkillRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/roadmaps': typeof RoadmapsRoute
  '/settings': typeof SettingsRoute
  '/templates/data-science': typeof TemplatesDataScienceRoute
  '/templates/ui-ux': typeof TemplatesUiUxRoute
  '/templates/web-dev': typeof TemplatesWebDevRoute
  '/templates/course/$id': typeof TemplatesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-skill': typeof AddSkillRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/roadmaps': typeof RoadmapsRoute
  '/settings': typeof SettingsRoute
  '/templates/data-science': typeof TemplatesDataScienceRoute
  '/templates/ui-ux': typeof TemplatesUiUxRoute
  '/templates/web-dev': typeof TemplatesWebDevRoute
  '/templates/course/$id': typeof TemplatesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-skill'
    | '/dashboard'
    | '/login'
    | '/roadmaps'
    | '/settings'
    | '/templates/data-science'
    | '/templates/ui-ux'
    | '/templates/web-dev'
    | '/templates/course/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-skill'
    | '/dashboard'
    | '/login'
    | '/roadmaps'
    | '/settings'
    | '/templates/data-science'
    | '/templates/ui-ux'
    | '/templates/web-dev'
    | '/templates/course/$id'
  id:
    | '__root__'
    | '/'
    | '/add-skill'
    | '/dashboard'
    | '/login'
    | '/roadmaps'
    | '/settings'
    | '/templates/data-science'
    | '/templates/ui-ux'
    | '/templates/web-dev'
    | '/templates/course/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddSkillRoute: typeof AddSkillRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RoadmapsRoute: typeof RoadmapsRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesDataScienceRoute: typeof TemplatesDataScienceRoute
  TemplatesUiUxRoute: typeof TemplatesUiUxRoute
  TemplatesWebDevRoute: typeof TemplatesWebDevRoute
  TemplatesCourseIdRoute: typeof TemplatesCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmaps': {
      id: '/roadmaps'
      path: '/roadmaps'
      fullPath: '/roadmaps'
      preLoaderRoute: typeof RoadmapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-skill': {
      id: '/add-skill'
      path: '/add-skill'
      fullPath: '/add-skill'
      preLoaderRoute: typeof AddSkillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/web-dev': {
      id: '/templates/web-dev'
      path: '/templates/web-dev'
      fullPath: '/templates/web-dev'
      preLoaderRoute: typeof TemplatesWebDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/ui-ux': {
      id: '/templates/ui-ux'
      path: '/templates/ui-ux'
      fullPath: '/templates/ui-ux'
      preLoaderRoute: typeof TemplatesUiUxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/data-science': {
      id: '/templates/data-science'
      path: '/templates/data-science'
      fullPath: '/templates/data-science'
      preLoaderRoute: typeof TemplatesDataScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/course/$id': {
      id: '/templates/course/$id'
      path: '/templates/course/$id'
      fullPath: '/templates/course/$id'
      preLoaderRoute: typeof TemplatesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddSkillRoute: AddSkillRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RoadmapsRoute: RoadmapsRoute,
  SettingsRoute: SettingsRoute,
  TemplatesDataScienceRoute: TemplatesDataScienceRoute,
  TemplatesUiUxRoute: TemplatesUiUxRoute,
  TemplatesWebDevRoute: TemplatesWebDevRoute,
  TemplatesCourseIdRoute: TemplatesCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
